# -*- coding: utf-8 -*-
"""Sơ đồ KLTN — PNG từ Mermaid + fallback ASCII."""

import os

_DIAGRAMS_DIR = os.path.join(os.path.dirname(os.path.abspath(__file__)), "diagrams")


def _img(filename):
    return os.path.join(_DIAGRAMS_DIR, filename)


DIAGRAMS = {
    "hinh_1_1_kien_truc_tong_quan": {
        "caption": "Hình 1.1: Kiến trúc tổng quan hệ thống Secure P2P Chat",
        "image": _img("hinh_1_1_kien_truc_tong_quan.png"),
        "lines": [
            "  ┌─────────────┐         HTTPS/WSS          ┌──────────────────────────┐",
            "  │  Flutter A  │◄──────────────────────────►│  Signaling Server        │",
            "  │  (Android)  │    REST + Socket.IO        │  (Render Cloud)          │",
            "  └──────┬──────┘                            │  • Auth JWT              │",
            "         │                                   │  • Room matching         │",
            "         │  WebRTC P2P (nếu NAT cho phép)     │  • Relay ciphertext      │",
            "         │         hoặc                        │  • KHÔNG lưu tin (mặc định)│",
            "         ▼         relay E2E qua server       └────────────┬─────────────┘",
            "  ┌─────────────┐         ▲                                  │",
            "  │  Flutter B  │─────────┘                                  │",
            "  │  (4G/WiFi)  │◄─────────────────────────────────────────────┘",
            "  └─────────────┘",
            "         │",
            "         ▼",
            "  ┌─────────────┐",
            "  │ SQLite local│  ← Lịch sử chat (plaintext sau giải mã E2E)",
            "  └─────────────┘",
        ],
    },
    "hinh_2_1_ngu_canh_he_thong": {
        "caption": "Hình 2.1: Sơ đồ ngữ cảnh hệ thống (Context Diagram)",
        "image": _img("hinh_2_1_ngu_canh.png"),
        "lines": [
            "                    ┌─────────────────────────────────────┐",
            "                    │         HỆ THỐNG SECURE P2P CHAT     │",
            "   Đăng ký/Đăng nhập│                                     │Gửi/nhận tin E2E",
            "   Nhập mã phòng    │   Flutter App  ◄──►  Signaling Srv   │Xem lịch sử local",
            "         ┌──────────┤                                     ├──────────┐",
            "         │          │   ChatSession / E2ECrypto / SQLite  │          │",
            "         ▼          └─────────────────────────────────────┘          ▼",
            "   ┌──────────┐                              ┌──────────┐      ┌──────────┐",
            "   │ Người    │                              │ Render   │      │ STUN     │",
            "   │ dùng A,B │                              │ (Cloud)  │      │ Google   │",
            "   └──────────┘                              └──────────┘      └──────────┘",
        ],
    },
    "hinh_2_2_luong_dang_ky": {
        "caption": "Hình 2.2: Luồng dữ liệu đăng ký tài khoản",
        "image": _img("hinh_2_2_dang_ky.png"),
        "lines": [
            "  [User]          [Flutter App]              [Signaling Server]",
            "    │                    │                            │",
            "    │ Nhập user/pass     │                            │",
            "    ├───────────────────►│                            │",
            "    │                    │ Sinh X25519 keypair        │",
            "    │                    │ POST /api/register         │",
            "    │                    │ {username, password,       │",
            "    │                    │  publicKey}                │",
            "    │                    ├───────────────────────────►│",
            "    │                    │                            │ bcrypt hash",
            "    │                    │                            │ lưu users.json",
            "    │                    │◄───────────────────────────┤",
            "    │                    │ {token, user}              │",
            "    │                    │ Lưu token + private key    │",
            "    │                    │   (SharedPreferences)      │",
            "    │◄───────────────────┤                            │",
            "    │ Vào màn phòng      │                            │",
        ],
    },
    "hinh_2_3_luong_vao_phong": {
        "caption": "Hình 2.3: Luồng dữ liệu vào phòng và ghép cặp peer",
        "image": _img("hinh_2_3_vao_phong.png"),
        "lines": [
            "  User A (App)              Server                 User B (App)",
            "      │                       │                         │",
            "      │ Socket authenticate   │   Socket authenticate   │",
            "      ├──────────────────────►│◄────────────────────────┤",
            "      │ join-room {KLTN2026}  │ join-room {KLTN2026}    │",
            "      ├──────────────────────►├────────────────────────►│",
            "      │                       │ roomStore ghép cùng phòng│",
            "      │◄─ room-joined {peers}─┤─► room-joined {peers} ──►│",
            "      │   thấy User B         │   thấy User A           │",
            "      │                       │                         │",
            "      │ Chọn B → ChatScreen   │                         │",
        ],
    },
    "hinh_2_4_luong_gui_tin_e2e": {
        "caption": "Hình 2.4: Luồng dữ liệu gửi tin nhắn E2E (relay mode)",
        "image": _img("hinh_2_4_gui_tin_e2e.png"),
        "lines": [
            "  Alice (App)                    Server                 Bob (App)",
            "      │                            │                        │",
            "      │ ECDH + HKDF → shared key   │                        │",
            "      │ AES-GCM encrypt(plaintext) │                        │",
            "      │                            │                        │",
            "      │ e2e-message {to:bob,       │                        │",
            "      │   payload: ciphertext}     │                        │",
            "      ├───────────────────────────►│ relay (không giải mã)  │",
            "      │                            ├───────────────────────►│",
            "      │                            │                        │ decrypt",
            "      │                            │                        │ hiển thị UI",
            "      │                            │                        │ lưu SQLite",
            "      │  messagesStored = 0        │  (chế độ mặc định)     │",
        ],
    },
    "hinh_2_5_cau_truc_flutter": {
        "caption": "Hình 2.5: Sơ đồ cấu trúc chương trình Flutter (phân tầng)",
        "image": _img("hinh_2_5_flutter_layers.png"),
        "lines": [
            "  ┌─────────────────────────────────────────────────────────┐",
            "  │  PRESENTATION (UI)                                       │",
            "  │  AuthGate → LoginScreen | RoomScreen | ChatScreen       │",
            "  │  DemoSettingsSheet                                       │",
            "  └───────────────────────────┬─────────────────────────────┘",
            "  ┌───────────────────────────▼─────────────────────────────┐",
            "  │  APPLICATION STATE                                       │",
            "  │  AppState — session, phòng, demo, ChatSession map        │",
            "  └───────────────────────────┬─────────────────────────────┘",
            "  ┌───────────────────────────▼─────────────────────────────┐",
            "  │  DOMAIN / BUSINESS LOGIC                                 │",
            "  │  ChatSession | E2ECrypto | PeerConnectionManager         │",
            "  └───────────────────────────┬─────────────────────────────┘",
            "  ┌───────────────────────────▼─────────────────────────────┐",
            "  │  INFRASTRUCTURE                                          │",
            "  │  AuthService | SignalingService | LocalDbService         │",
            "  │  DemoService                                             │",
            "  └─────────────────────────────────────────────────────────┘",
        ],
    },
    "hinh_2_6_cau_truc_server": {
        "caption": "Hình 2.6: Sơ đồ cấu trúc chương trình Signaling Server",
        "image": _img("hinh_2_6_server_modules.png"),
        "lines": [
            "  server.js (Express + Socket.IO)",
            "       │",
            "       ├── REST API ──────► userStore.js ──► users.json",
            "       │                    roomStore.js (in-memory)",
            "       │                    demoSettings.js",
            "       │                    messageStore.js (demo only)",
            "       │",
            "       ├── /health ─────────► healthPage.js (HTML dashboard)",
            "       │",
            "       └── Socket.IO ─────► handlers.js",
            "                              • authenticate (JWT)",
            "                              • join-room / room-users",
            "                              • webrtc-offer/answer/ice",
            "                              • e2e-message (relay)",
        ],
    },
    "hinh_2_7_sequence_chat": {
        "caption": "Hình 2.7: Biểu đồ trình tự (Sequence) — bắt đầu chat E2E",
        "image": _img("hinh_2_7_bat_dau_chat.png"),
        "lines": [
            "  User    RoomScreen   AppState   ChatSession   Signaling   Peer",
            "    │         │           │            │            │         │",
            "    │ Chọn peer│           │            │            │         │",
            "    ├────────►│           │            │            │         │",
            "    │         ├──────────►│ connectToPeer()         │         │",
            "    │         │           ├───────────►│ start()    │         │",
            "    │         │           │            ├─ derive key│         │",
            "    │         │           │            ├─ relay ON  │         │",
            "    │         │           │            ├───────────►│ try P2P │",
            "    │ Gửi tin │           │            │            │         │",
            "    ├────────►│ sendMessage()        │            │         │",
            "    │         │           ├───────────►│ encrypt    │         │",
            "    │         │           │            ├───────────►│ e2e-msg │",
            "    │         │           │            │            ├───────►│ decrypt",
        ],
    },
    "hinh_2_8_csdl_local": {
        "caption": "Hình 2.8: Sơ đồ CSDL SQLite trên thiết bị",
        "image": _img("hinh_2_8_sqlite_er.png"),
        "lines": [
            "  ┌─────────────────────────────────────┐",
            "  │            messages                  │",
            "  ├──────────────┬──────────────────────┤",
            "  │ id (PK)      │ INTEGER AUTO         │",
            "  │ peer_username│ TEXT                 │",
            "  │ content      │ TEXT (sau decrypt)   │",
            "  │ is_mine      │ INTEGER (0/1)        │",
            "  │ timestamp    │ INTEGER              │",
            "  │ encrypted    │ INTEGER (flag E2E)   │",
            "  └──────────────┴──────────────────────┘",
            "  ┌─────────────────────────────────────┐",
            "  │          conversations               │",
            "  ├──────────────┬──────────────────────┤",
            "  │ peer_username│ TEXT (PK)            │",
            "  │ last_message │ TEXT                 │",
            "  │ last_timestamp│ INTEGER             │",
            "  └──────────────┴──────────────────────┘",
        ],
    },
}
